---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    author: hbc
spec:
  containers:
    - name: mynginx
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: slavename
                operator: In
                values:
                  - hbc
...
