---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      author: intelliqit
  template:
    metadata:
      name: mysql-pod
      labels:
        author: intelliqit
    spec:
      containers:
        - name: mydb
          image: mysql:5
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: intelliqit
      tolerations:
        - key: node2
          operator: Equal
          value: intelliqit2
          effect: NoSchedule
         
