---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    type: db
    author: intelliqit
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: intelliqit
  tolerations:
    - key: node1
      operator: Equal
      value: intelliqit1
      effect: NoSchedule
...
