---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
  type: proxy
spec:
 replicas: 2
 selector:
  matchLabels:
   type: proxy
 template:
  metadata:
   name: nginx-pod
   labels:
    type: proxy
  spec:
   containers:
    - name: myngninx
      image: nginx
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 type: NodePort
 ports:
  - targetPort: 80
    port: 80
 selector:
  type: proxy

